services:
  - type: web
    name: fire-camera-detector
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --threads 8 --timeout 0 -b 0.0.0.0:$PORT dashboard:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
